project:
  type: website
  output-dir: docs

website:
  favicon: assets/spwla_id_logo-2.png
  title: "SPWLA Indonesia"
  repo-url: https://github.com/ariewjy/spwla-indonesia-website
  repo-actions: [edit]
  # sidebar:
  #   style: docked
  navbar:
    background: "#1d3557"
    # foreground: "#fb8500"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/spwla-chapter-indonesia-785648172/
      - icon: instagram
        href: https://www.instagram.com/spwla_indonesia/
      - href: submission.qmd
        text: Submission

    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: event.qmd
        text: Event
  open-graph: true
  search:
    location: navbar
    type: overlay

format:
  html:
    theme: [styles.scss]
    css: styles.scss
    toc: true
fig-cap-location: bottom
fig-responsive: true
