project:
  type: website
  output-dir: docs

website:
  title: "SPWLA Indonesia Chapter"
  navbar:
    background: "#1d3557"
    # foreground: "#fb8500"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: litera
    css: styles.scss
    toc: true
