project:
  type: website
  output-dir: docs

website:
  favicon: assets/spwla_id_logo-2.png
  title: "SPWLA Indonesia"
  navbar:
    background: "#1d3557"
    # foreground: "#fb8500"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  open-graph: true

format:
  html:
    theme: [styles.scss]
    css: styles.scss
    toc: true
fig-cap-location: bottom
fig-responsive: true
